[2020-09-21 22:36:38,217] INFO Expiring session 0x10001aee5ca0000, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2020-09-21 22:36:37,577] WARN Attempting to send response via channel for which there is no open connection, connection id 192.168.56.1:9092-192.168.56.1:58787-2 (kafka.network.Processor)
[2020-09-21 22:36:38,594] WARN Client session timed out, have not heard from server in 5332095ms for sessionid 0x10001aee5ca0000 (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:36:38,660] INFO Client session timed out, have not heard from server in 5332095ms for sessionid 0x10001aee5ca0000, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:36:40,056] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:36:40,139] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:61082, server: localhost/0:0:0:0:0:0:0:1:2181 (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:36:40,227] INFO Invalid session 0x10001aee5ca0000 for client /0:0:0:0:0:0:0:1:61082, probably expired (org.apache.zookeeper.server.ZooKeeperServer)
[2020-09-21 22:36:40,232] WARN Unable to reconnect to ZooKeeper service, session 0x10001aee5ca0000 has expired (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:36:40,234] INFO EventThread shut down for session: 0x10001aee5ca0000 (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:36:40,308] INFO Unable to reconnect to ZooKeeper service, session 0x10001aee5ca0000 has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:36:40,315] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2020-09-21 22:36:40,318] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2020-09-21 22:36:40,343] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@35229f85 (org.apache.zookeeper.ZooKeeper)
[2020-09-21 22:36:40,367] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2020-09-21 22:36:40,447] INFO zookeeper.request.timeout value is 0. feature enabled= (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:36:40,719] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:36:40,722] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.zk.KafkaZkClient)
[2020-09-21 22:36:40,760] INFO Socket connection established, initiating session, client: /127.0.0.1:61085, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:36:40,807] INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x10001aee5ca0001, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:36:40,833] INFO Stat of the created znode at /brokers/ids/0 is: 141,141,1600708000821,1600708000821,1,0,0,72059444729085953,200,0,141
 (kafka.zk.KafkaZkClient)
[2020-09-21 22:36:40,895] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT://DESKTOP-JP0D9RM:9092, czxid (broker epoch): 141 (kafka.zk.KafkaZkClient)
[2020-09-21 22:39:47,171] WARN Session 0x10001aee5ca0001 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
[2020-09-21 22:39:48,709] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:39:50,714] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused: no further information (org.apache.zookeeper.ClientCnxn)
[2020-09-21 22:39:50,817] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
